"use client";

import { usePathname } from "next/navigation";
import { useState } from "react";

// Docs pages ship a Markdown twin at /llms/<path>.md (generated by
// scripts/gen-llms.mjs). This toolbar lets a reader hand the current page to an
// LLM in one click — copy the raw Markdown, open it, or jump straight into
// ChatGPT / Claude with a prompt pointing at it.

const SITE = "https://docs.0gkit.com";

function mdHref(pathname: string): string {
  const clean = pathname.replace(/\/+$/, "");
  const slug = clean === "" ? "index" : clean.replace(/^\//, "");
  return `/llms/${slug}.md`;
}

type CopyState = "idle" | "copied" | "error";

export function CopyForLLM() {
  const pathname = usePathname() || "/";
  const [state, setState] = useState<CopyState>("idle");

  const md = mdHref(pathname);
  const mdUrl = `${SITE}${md}`;
  const prompt = `Read ${mdUrl} — it is the Markdown for a page of the 0Gkit docs. Use it to answer my questions about 0Gkit.`;
  const chatgpt = `https://chatgpt.com/?q=${encodeURIComponent(prompt)}`;
  const claude = `https://claude.ai/new?q=${encodeURIComponent(prompt)}`;

  async function copy() {
    try {
      let text = "";
      try {
        const res = await fetch(md, { cache: "no-store" });
        if (res.ok) text = await res.text();
      } catch {
        /* fall through to the rendered-text fallback below */
      }
      if (!text) {
        // Dev / offline fallback: copy the rendered article text.
        const prose = document.querySelector(".prose") as HTMLElement | null;
        text = `# ${document.title}\nSource: ${SITE}${pathname}\n\n${
          prose?.innerText?.trim() ?? ""
        }`;
      }
      await navigator.clipboard.writeText(text);
      setState("copied");
    } catch {
      setState("error");
    }
    window.setTimeout(() => setState("idle"), 2000);
  }

  const copyLabel =
    state === "copied"
      ? "Copied ✓"
      : state === "error"
        ? "Copy failed"
        : "Copy for LLM";

  return (
    <div className="page-actions" role="group" aria-label="Use this page with an LLM">
      <button
        type="button"
        className="page-action page-action-primary"
        onClick={copy}
        aria-live="polite"
      >
        <CopyIcon />
        {copyLabel}
      </button>
      <a className="page-action" href={md} target="_blank" rel="noreferrer">
        View as Markdown
      </a>
      <a className="page-action" href={chatgpt} target="_blank" rel="noreferrer">
        Open in ChatGPT
      </a>
      <a className="page-action" href={claude} target="_blank" rel="noreferrer">
        Open in Claude
      </a>
    </div>
  );
}

function CopyIcon() {
  return (
    <svg
      width="13"
      height="13"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  );
}
