// AUTO-GENERATED by scripts/gen-registry.mjs — DO NOT EDIT BY HAND
// Regenerated on every build via the "prebuild" / "pretest" npm script.
import type { KitManifest } from "./manifest.js";

export const KITS: KitManifest[] = [
  {
    name: "agent-memory",
    title: "Agent Memory",
    domain: "agent-infra",
    summary:
      "Persistent agent memory on 0G Storage — append-only JSONL blobs per namespace with keyword-indexed recall.",
    compatibleBases: ["react-app", "chat", "storage-app", "mcp-agent"],
    tiers: {
      lib: ["lib/agent-memory.ts"],
      adapters: {
        "mcp-agent": ["src/tools/memory.ts"],
        "react-app": ["app/api/memory/route.ts"],
      },
      ui: ["components/MemoryPanel.tsx", "hooks/useAgentMemory.ts"],
    },
    env: [
      {
        key: "OG_STORAGE_NAMESPACE",
        example: "agent-memory",
        note: "Namespace prefix for memory blobs in 0G Storage",
      },
      {
        key: "OG_PRIVATE_KEY",
        example: "0x...",
        note: "Private key for signing 0G Storage transactions",
      },
      {
        key: "OG_RPC_URL",
        example: "https://evmrpc-testnet.0g.ai",
        note: "0G chain RPC endpoint",
      },
    ],
    dependencies: {
      "@foundryprotocol/0gkit-storage": "^1.0.0",
    },
    devDependencies: {},
    requires: [],
    composes: [],
    conflicts: [],
  },
  {
    name: "ai-oracle",
    title: "AI Oracle",
    domain: "verifiable-ai",
    summary:
      "Signed AI answers with commitments anchored to 0G Storage (default) or on-chain. Each answer is hashed, signed by the operator key (✓ signature verified — not TEE-quote), and anchored as an immutable proof. Composes into prediction-market.",
    compatibleBases: ["react-app", "chat", "tee-attested-api", "mcp-agent"],
    tiers: {
      lib: ["lib/oracle.ts", "lib/anchor-abi.ts"],
      adapters: {
        "react-app": ["app/api/oracle/route.ts"],
        chat: ["app/api/oracle/route.ts"],
        "tee-attested-api": ["src/routes/oracle.ts"],
        "mcp-agent": ["src/tools/oracle.ts"],
      },
    },
    env: [
      {
        key: "OG_COMPUTE_MODEL",
        example: "neuralmagic/Meta-Llama-3.1-70B-Instruct-FP8",
        note: "Model to use for AI inference (optional — uses provider default if omitted)",
      },
      {
        key: "OG_PRIVATE_KEY",
        example: "0x...",
        note: "Operator private key for signing inference receipts and 0G transactions",
      },
      {
        key: "OG_RPC_URL",
        example: "https://evmrpc-testnet.0g.ai",
        note: "0G chain RPC endpoint",
      },
      {
        key: "OG_ANCHOR_ONCHAIN",
        example: "1",
        note: "Set to '1' to commit oracle receipts on-chain via Anchor.sol (default: 0G Storage)",
      },
      {
        key: "OG_ANCHOR_ADDRESS",
        example: "0x...",
        note: "Deployed Anchor contract address — required when OG_ANCHOR_ONCHAIN=1",
      },
    ],
    dependencies: {
      "@foundryprotocol/0gkit-compute": "^1.0.0",
      "@foundryprotocol/0gkit-attestation": "^1.0.0",
      "@foundryprotocol/0gkit-storage": "^1.0.0",
      "@foundryprotocol/0gkit-contracts": "^1.0.0",
      "@foundryprotocol/0gkit-wallet": "^1.0.0",
    },
    devDependencies: {},
    requires: [],
    composes: [],
    conflicts: [],
  },
  {
    name: "prediction-market",
    title: "Prediction Market",
    domain: "markets",
    summary:
      "AI-resolved, proof-anchored prediction market. Lifecycle: open → bet → resolve (via the ai-oracle) → settle. Composes ai-oracle so applying prediction-market auto-applies ai-oracle first. Resolution receipts are signed by the operator key (✓ signature verified — not TEE-quote) and anchored to 0G Storage (or on-chain opt-in).",
    compatibleBases: ["react-app", "chat", "tee-attested-api"],
    tiers: {
      lib: ["lib/market.ts"],
      adapters: {
        "react-app": ["app/api/markets/route.ts"],
        chat: ["app/api/markets/route.ts"],
        "tee-attested-api": ["src/routes/markets.ts"],
      },
      ui: [
        "app/markets/page.tsx",
        "components/MarketBoard.tsx",
        "components/CreateMarketForm.tsx",
      ],
    },
    env: [
      {
        key: "OG_COMPUTE_MODEL",
        example: "neuralmagic/Meta-Llama-3.1-70B-Instruct-FP8",
        note: "Model to use for AI oracle inference (optional — uses provider default if omitted)",
      },
      {
        key: "OG_PRIVATE_KEY",
        example: "0x...",
        note: "Operator private key for signing resolution receipts and 0G transactions",
      },
      {
        key: "OG_RPC_URL",
        example: "https://evmrpc-testnet.0g.ai",
        note: "0G chain RPC endpoint",
      },
      {
        key: "OG_ANCHOR_ONCHAIN",
        example: "1",
        note: "Set to '1' to commit resolution receipts on-chain via Anchor.sol (default: 0G Storage)",
      },
      {
        key: "OG_ANCHOR_ADDRESS",
        example: "0x...",
        note: "Deployed Anchor contract address — required when OG_ANCHOR_ONCHAIN=1",
      },
      {
        key: "OG_STORAGE_NAMESPACE",
        example: "prediction-market",
        note: "Namespace prefix for market blobs in 0G Storage",
      },
    ],
    dependencies: {
      "@foundryprotocol/0gkit-compute": "^1.0.0",
      "@foundryprotocol/0gkit-attestation": "^1.0.0",
      "@foundryprotocol/0gkit-storage": "^1.0.0",
      "@foundryprotocol/0gkit-contracts": "^1.0.0",
      "@foundryprotocol/0gkit-wallet": "^1.0.0",
      "@foundryprotocol/0gkit-core": "^1.0.0",
    },
    devDependencies: {},
    requires: [],
    composes: ["ai-oracle"],
    conflicts: [],
  },
  {
    name: "sealed-inference",
    title: "Sealed Inference",
    domain: "verifiable-ai",
    summary:
      "Signed AI inference with a verification badge driven by the real verify result. Each response is signed by the operator key (✓ signature verified — not TEE-quote), and the UI badge reflects the actual verification outcome — never hardcoded, never always-green.",
    compatibleBases: ["react-app", "chat", "tee-attested-api", "mcp-agent"],
    tiers: {
      lib: ["lib/sealed.ts"],
      adapters: {
        "react-app": ["app/api/sealed/route.ts"],
        chat: ["app/api/sealed/route.ts"],
        "tee-attested-api": ["src/routes/sealed.ts"],
        "mcp-agent": ["src/tools/sealed.ts"],
      },
      ui: ["components/SealedChat.tsx", "hooks/useSealedInference.ts"],
    },
    env: [
      {
        key: "OG_COMPUTE_MODEL",
        example: "neuralmagic/Meta-Llama-3.1-70B-Instruct-FP8",
        note: "Model to use for AI inference (optional — uses provider default if omitted)",
      },
      {
        key: "OG_PRIVATE_KEY",
        example: "0x...",
        note: "Operator private key for signing inference receipts and 0G transactions",
      },
      {
        key: "OG_RPC_URL",
        example: "https://evmrpc-testnet.0g.ai",
        note: "0G chain RPC endpoint",
      },
      {
        key: "OG_ATTESTOR_ADDRESS",
        example: "0x...",
        note: "Expected signer address — the operator address whose signature verify() checks against",
      },
    ],
    dependencies: {
      "@foundryprotocol/0gkit-compute": "^1.0.0",
      "@foundryprotocol/0gkit-attestation": "^1.0.0",
      "@foundryprotocol/0gkit-wallet": "^1.0.0",
    },
    devDependencies: {},
    requires: [],
    composes: [],
    conflicts: [],
  },
];
