// AUTO-GENERATED by scripts/gen-registry.mjs — DO NOT EDIT BY HAND
// Regenerated on every build via the "prebuild" / "pretest" npm script.
import type { KitManifest } from "./manifest.js";

export const KITS: KitManifest[] = [];
