// AUTO-GENERATED by scripts/gen-registry.mjs — DO NOT EDIT BY HAND
// Regenerated on every build via the "prebuild" / "pretest" npm script.
import type { KitManifest } from "./manifest.js";

export const KITS: KitManifest[] = [
  {
    name: "agent-memory",
    title: "Agent Memory",
    domain: "agent-infra",
    summary:
      "Persistent agent memory on 0G Storage — append-only JSONL blobs per namespace with keyword-indexed recall.",
    compatibleBases: ["react-app", "chat", "storage-app", "mcp-agent"],
    tiers: {
      lib: ["lib/agent-memory.ts"],
      adapters: {
        "mcp-agent": ["src/tools/memory.ts"],
        "react-app": ["app/api/memory/route.ts"],
      },
      ui: ["components/MemoryPanel.tsx", "hooks/useAgentMemory.ts"],
    },
    env: [
      {
        key: "OG_STORAGE_NAMESPACE",
        example: "agent-memory",
        note: "Namespace prefix for memory blobs in 0G Storage",
      },
      {
        key: "OG_PRIVATE_KEY",
        example: "0x...",
        note: "Private key for signing 0G Storage transactions",
      },
      {
        key: "OG_RPC_URL",
        example: "https://evmrpc-testnet.0g.ai",
        note: "0G chain RPC endpoint",
      },
    ],
    dependencies: {
      "@foundryprotocol/0gkit-storage": "^1.0.0",
    },
    devDependencies: {},
    requires: [],
    composes: [],
    conflicts: [],
  },
  {
    name: "ai-oracle",
    title: "AI Oracle",
    domain: "verifiable-ai",
    summary:
      "Signed AI answers with commitments anchored to 0G Storage (default) or on-chain. Each answer is hashed, signed by the operator key (✓ signature verified — not TEE-quote), and anchored as an immutable proof. Composes into prediction-market.",
    compatibleBases: ["react-app", "chat", "tee-attested-api", "mcp-agent"],
    tiers: {
      lib: ["lib/oracle.ts", "lib/anchor-abi.ts"],
      adapters: {
        "react-app": ["app/api/oracle/route.ts"],
        chat: ["app/api/oracle/route.ts"],
        "tee-attested-api": ["src/routes/oracle.ts"],
        "mcp-agent": ["src/tools/oracle.ts"],
      },
    },
    env: [
      {
        key: "OG_COMPUTE_MODEL",
        example: "neuralmagic/Meta-Llama-3.1-70B-Instruct-FP8",
        note: "Model to use for AI inference (optional — uses provider default if omitted)",
      },
      {
        key: "OG_PRIVATE_KEY",
        example: "0x...",
        note: "Operator private key for signing inference receipts and 0G transactions",
      },
      {
        key: "OG_RPC_URL",
        example: "https://evmrpc-testnet.0g.ai",
        note: "0G chain RPC endpoint",
      },
      {
        key: "OG_ANCHOR_ONCHAIN",
        example: "1",
        note: "Set to '1' to commit oracle receipts on-chain via Anchor.sol (default: 0G Storage)",
      },
      {
        key: "OG_ANCHOR_ADDRESS",
        example: "0x...",
        note: "Deployed Anchor contract address — required when OG_ANCHOR_ONCHAIN=1",
      },
    ],
    dependencies: {
      "@foundryprotocol/0gkit-compute": "^1.0.0",
      "@foundryprotocol/0gkit-attestation": "^1.0.0",
      "@foundryprotocol/0gkit-storage": "^1.0.0",
      "@foundryprotocol/0gkit-contracts": "^1.0.0",
      "@foundryprotocol/0gkit-wallet": "^1.0.0",
      "@foundryprotocol/0gkit-core": "^1.0.0",
    },
    devDependencies: {},
    requires: [],
    composes: [],
    conflicts: [],
  },
  {
    name: "durable-agent",
    title: "Durable Agent",
    domain: "agent-infra",
    summary:
      "Resumable multi-step agent loop on 0gkit-jobs — step ledger persisted to 0G Storage prevents re-running completed steps on restart, every executed step is traced via OpenTelemetry. Optional sealed-inference step is capability-guarded (runtime check, not a hard dep).",
    compatibleBases: [
      "react-app",
      "chat",
      "tee-attested-api",
      "mcp-agent",
      "storage-app",
    ],
    tiers: {
      lib: ["agent.ts", "steps.ts"],
      adapters: {
        "react-app": ["app/api/agent/route.ts"],
        chat: ["app/api/agent/route.ts"],
        "tee-attested-api": ["src/routes/agent.ts"],
        "mcp-agent": ["src/tools/agent.ts"],
        "storage-app": ["src/agent-runner.ts"],
      },
    },
    env: [
      {
        key: "OG_PRIVATE_KEY",
        example: "0xabc123...",
        note: "0x-prefixed private key — required for 0gkit-jobs signer (signing job receipts) and 0G Storage (uploading/downloading the durable step ledger)",
      },
      {
        key: "OG_RPC_URL",
        example: "https://rpc.0g.ai",
        note: "0G chain RPC URL — required for 0G Storage operations (step-ledger persistence)",
      },
      {
        key: "OG_STORAGE_NAMESPACE",
        example: "durable-agent",
        note: "Namespace prefix for 0G Storage step-ledger blobs (default: 'durable-agent'). Each run's ledger is stored under <namespace>/<jobId>/steps.",
      },
      {
        key: "OG_JOBS_BACKEND",
        example: "memory",
        note: "Informational — documents the active jobs backend. 'memory' = MemoryBackend (in-process, default, dev-friendly). Swap to 'sqlite' by importing SqliteBackend from @foundryprotocol/0gkit-jobs/backends/sqlite for cross-process job durability.",
      },
    ],
    dependencies: {
      "@foundryprotocol/0gkit-jobs": "^1.0.0",
      "@foundryprotocol/0gkit-storage": "^1.0.0",
      "@foundryprotocol/0gkit-wallet": "^1.0.0",
      "@opentelemetry/api": "^1.9.0",
      zod: "^3.23.0",
    },
    devDependencies: {},
    requires: [],
    composes: [],
    conflicts: [],
  },
  {
    name: "inft-studio",
    title: "iNFT Studio",
    domain: "assets",
    summary:
      "Mint intelligent NFTs with AI-generated media stored on 0G Storage and attested provenance. Media+metadata uploaded content-addressed; minted via a typed INFT contract (Inft.sol — standard ERC-721 has no mint). Optional signed provenance receipt ties model+prompt to the content hash (✓ signature verified — not TEE-quote).",
    compatibleBases: ["react-app", "chat"],
    tiers: {
      lib: ["lib/inft.ts", "lib/inft-abi.ts"],
      adapters: {
        "react-app": [
          "app/api/inft/mint/route.ts",
          "app/api/inft/token/route.ts",
          "app/api/inft/tokens/route.ts",
          "app/api/inft/verify/route.ts",
        ],
        chat: [
          "app/api/inft/mint/route.ts",
          "app/api/inft/token/route.ts",
          "app/api/inft/tokens/route.ts",
          "app/api/inft/verify/route.ts",
        ],
      },
      ui: [
        "components/MintForm.tsx",
        "components/Gallery.tsx",
        "components/ProvenanceBadge.tsx",
        "app/studio/page.tsx",
      ],
    },
    env: [
      {
        key: "OG_PRIVATE_KEY",
        example: "0x...",
        note: "Operator private key for signing 0G Storage transactions and provenance receipts",
      },
      {
        key: "OG_RPC_URL",
        example: "https://evmrpc-testnet.0g.ai",
        note: "0G chain RPC endpoint",
      },
      {
        key: "OG_INFT_ADDRESS",
        example: "0x...",
        note: "Deployed Inft.sol contract address — deploy via contracts/script/DeployInft.s.sol",
      },
      {
        key: "OG_COMPUTE_MODEL",
        example: "neuralmagic/Meta-Llama-3.1-70B-Instruct-FP8",
        note: "Default AI model for provenance attestation (optional)",
      },
    ],
    dependencies: {
      "@foundryprotocol/0gkit-storage": "^1.0.0",
      "@foundryprotocol/0gkit-contracts": "^1.0.0",
      "@foundryprotocol/0gkit-attestation": "^1.0.0",
      "@foundryprotocol/0gkit-wallet": "^1.0.0",
      "@foundryprotocol/0gkit-core": "^1.0.0",
    },
    devDependencies: {},
    requires: [],
    composes: [],
    conflicts: [],
  },
  {
    name: "live-feed",
    title: "Live Feed",
    domain: "markets",
    summary:
      "Reorg-safe live social feed on 0G Storage + 0gkit-indexer. Posts are content-addressed blobs in 0G Storage; ordering and reorg-safety come from the Indexer tracking on-chain PostPublished events (requires a deployed FeedEvents contract). Falls back to storage-only mode without a contract address.",
    compatibleBases: ["react-app", "chat"],
    tiers: {
      lib: ["lib/feed.ts"],
      adapters: {
        "react-app": ["app/api/feed/route.ts"],
        chat: ["app/api/feed/route.ts"],
      },
      ui: ["hooks/useLiveFeed.ts", "components/FeedStream.tsx", "app/feed/page.tsx"],
    },
    env: [
      {
        key: "OG_PRIVATE_KEY",
        example: "0x...",
        note: "0x-prefixed private key for signing 0G Storage transactions (required)",
      },
      {
        key: "OG_RPC_URL",
        example: "https://evmrpc-testnet.0g.ai",
        note: "0G chain RPC endpoint (required for Storage and Indexer)",
      },
      {
        key: "OG_FEED_CONTRACT_ADDRESS",
        example: "0xYourDeployedFeedEventsContract",
        note: "Deployed FeedEvents contract address. When set, enables real Indexer reorg-safety. Without it, the adapter runs in storage-only mode (posts are stored but reorg-drop is not active).",
      },
      {
        key: "OG_FEED_NAMESPACE",
        example: "live-feed",
        note: "Storage namespace prefix for feed blobs (default: live-feed)",
      },
    ],
    dependencies: {
      "@foundryprotocol/0gkit-storage": "^1.0.0",
      "@foundryprotocol/0gkit-indexer": "^1.0.0",
    },
    devDependencies: {},
    requires: [],
    composes: [],
    conflicts: [],
  },
  {
    name: "prediction-market",
    title: "Prediction Market",
    domain: "markets",
    summary:
      "AI-resolved, proof-anchored prediction market. Lifecycle: open → bet → resolve (via the ai-oracle) → settle. Composes ai-oracle so applying prediction-market auto-applies ai-oracle first. Resolution receipts are signed by the operator key (✓ signature verified — not TEE-quote) and anchored to 0G Storage (or on-chain opt-in).",
    compatibleBases: ["react-app", "chat", "tee-attested-api"],
    tiers: {
      lib: ["lib/market.ts"],
      adapters: {
        "react-app": ["app/api/markets/route.ts"],
        chat: ["app/api/markets/route.ts"],
        "tee-attested-api": ["src/routes/markets.ts"],
      },
      ui: [
        "app/markets/page.tsx",
        "components/MarketBoard.tsx",
        "components/CreateMarketForm.tsx",
      ],
    },
    env: [
      {
        key: "OG_COMPUTE_MODEL",
        example: "neuralmagic/Meta-Llama-3.1-70B-Instruct-FP8",
        note: "Model to use for AI oracle inference (optional — uses provider default if omitted)",
      },
      {
        key: "OG_PRIVATE_KEY",
        example: "0x...",
        note: "Operator private key for signing resolution receipts and 0G transactions",
      },
      {
        key: "OG_RPC_URL",
        example: "https://evmrpc-testnet.0g.ai",
        note: "0G chain RPC endpoint",
      },
      {
        key: "OG_ANCHOR_ONCHAIN",
        example: "1",
        note: "Set to '1' to commit resolution receipts on-chain via Anchor.sol (default: 0G Storage)",
      },
      {
        key: "OG_ANCHOR_ADDRESS",
        example: "0x...",
        note: "Deployed Anchor contract address — required when OG_ANCHOR_ONCHAIN=1",
      },
      {
        key: "OG_STORAGE_NAMESPACE",
        example: "prediction-market",
        note: "Namespace prefix for market blobs in 0G Storage",
      },
    ],
    dependencies: {
      "@foundryprotocol/0gkit-compute": "^1.0.0",
      "@foundryprotocol/0gkit-attestation": "^1.0.0",
      "@foundryprotocol/0gkit-storage": "^1.0.0",
      "@foundryprotocol/0gkit-contracts": "^1.0.0",
      "@foundryprotocol/0gkit-wallet": "^1.0.0",
      "@foundryprotocol/0gkit-core": "^1.0.0",
    },
    devDependencies: {},
    requires: [],
    composes: ["ai-oracle"],
    conflicts: [],
  },
  {
    name: "sealed-inference",
    title: "Sealed Inference",
    domain: "verifiable-ai",
    summary:
      "Signed AI inference with a verification badge driven by the real verify result. Each response is signed by the operator key (✓ signature verified — not TEE-quote), and the UI badge reflects the actual verification outcome — never hardcoded, never always-green.",
    compatibleBases: ["react-app", "chat", "tee-attested-api", "mcp-agent"],
    tiers: {
      lib: ["lib/sealed.ts"],
      adapters: {
        "react-app": ["app/api/sealed/route.ts"],
        chat: ["app/api/sealed/route.ts"],
        "tee-attested-api": ["src/routes/sealed.ts"],
        "mcp-agent": ["src/tools/sealed.ts"],
      },
      ui: ["components/SealedChat.tsx", "hooks/useSealedInference.ts"],
    },
    env: [
      {
        key: "OG_COMPUTE_MODEL",
        example: "neuralmagic/Meta-Llama-3.1-70B-Instruct-FP8",
        note: "Model to use for AI inference (optional — uses provider default if omitted)",
      },
      {
        key: "OG_PRIVATE_KEY",
        example: "0x...",
        note: "Operator private key for signing inference receipts and 0G transactions",
      },
      {
        key: "OG_RPC_URL",
        example: "https://evmrpc-testnet.0g.ai",
        note: "0G chain RPC endpoint",
      },
      {
        key: "OG_ATTESTOR_ADDRESS",
        example: "0x...",
        note: "Expected signer address — the operator address whose signature verify() checks against",
      },
    ],
    dependencies: {
      "@foundryprotocol/0gkit-compute": "^1.0.0",
      "@foundryprotocol/0gkit-attestation": "^1.0.0",
      "@foundryprotocol/0gkit-wallet": "^1.0.0",
      "@foundryprotocol/0gkit-core": "^1.0.0",
    },
    devDependencies: {},
    requires: [],
    composes: [],
    conflicts: [],
  },
];
